package format

import (
	"bytes"
	"fmt"
	"html"
	"sort"
	"strings"
	"time"

	"github.com/cerberauth/reportx"
)

type HTMLFormatter struct{}

func NewHTMLFormatter() *HTMLFormatter { return &HTMLFormatter{} }

var htmlSeverityOrder = []reportx.Severity{
	reportx.SeverityCritical,
	reportx.SeverityHigh,
	reportx.SeverityMedium,
	reportx.SeverityLow,
	reportx.SeverityInfo,
}

var htmlSeverityColors = map[reportx.Severity]string{
	reportx.SeverityCritical: "#d32f2f",
	reportx.SeverityHigh:     "#f57c00",
	reportx.SeverityMedium:   "#f9a825",
	reportx.SeverityLow:      "#1976d2",
	reportx.SeverityInfo:     "#616161",
}

const htmlStyles = `
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f5f5f5;color:#212121;line-height:1.5}
.header{background:#fff;border-bottom:1px solid #e0e0e0;padding:1.5rem 2rem}
.header h1{font-size:1.5rem;font-weight:600}
.meta{color:#757575;font-size:.875rem;margin-top:.25rem}
.summary{display:flex;gap:1rem;padding:1.5rem 2rem;flex-wrap:wrap}
.badge{background:#fff;border-radius:8px;border-left:4px solid;padding:.75rem 1rem;min-width:100px;box-shadow:0 1px 3px rgba(0,0,0,.1)}
.badge .count{font-size:1.75rem;font-weight:700}
.badge .label{font-size:.75rem;text-transform:uppercase;letter-spacing:.05em;color:#757575}
.section{padding:0 2rem 2rem}
.section h2{font-size:1.125rem;font-weight:600;margin-bottom:1rem;padding-top:1rem}
details{background:#fff;border-radius:6px;box-shadow:0 1px 3px rgba(0,0,0,.1);margin-bottom:.5rem;overflow:hidden}
summary{cursor:pointer;padding:.875rem 1rem;font-weight:500;list-style:none;display:flex;align-items:center;gap:.5rem;user-select:none}
summary::-webkit-details-marker{display:none}
summary::before{content:'▶';font-size:.6rem;transition:transform .15s;flex-shrink:0}
details[open] summary::before{transform:rotate(90deg)}
.sev{border-radius:4px;color:#fff;font-size:.7rem;font-weight:700;padding:.1rem .4rem;text-transform:uppercase;flex-shrink:0}
.finding-body{border-top:1px solid #e0e0e0;padding:1rem}
dl{display:grid;grid-template-columns:max-content 1fr;gap:.25rem 1rem;font-size:.875rem}
dt{font-weight:500;color:#616161}
dd{word-break:break-word}
.prose{margin-top:.75rem;font-size:.875rem}
.prose h4{font-weight:600;margin-bottom:.25rem}
pre{background:#f5f5f5;border-radius:4px;font-size:.75rem;overflow-x:auto;padding:.75rem;margin-top:.5rem;white-space:pre-wrap;word-break:break-word}
@media print{
body{background:#fff}
.summary{display:none}
details{box-shadow:none;border:1px solid #e0e0e0;display:block}
summary::before{display:none}
.finding-body{display:block!important}
}
`

func (f *HTMLFormatter) Format(r *reportx.Report) ([]byte, error) {
	var buf bytes.Buffer

	title := r.Title
	if title == "" {
		title = defaultTitle
	}

	buf.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
	buf.WriteString("<meta charset=\"utf-8\">\n")
	buf.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	fmt.Fprintf(&buf, "<meta name=\"generator\" content=\"%s\">\n", html.EscapeString(reportx.Watermark))
	fmt.Fprintf(&buf, "<title>%s</title>\n", html.EscapeString(title))
	fmt.Fprintf(&buf, "<style>%s</style>\n", htmlStyles)
	buf.WriteString("</head>\n<body>\n")

	fmt.Fprintf(&buf, "<div class=\"header\"><h1>%s</h1>\n", html.EscapeString(title))
	fmt.Fprintf(&buf, "<div class=\"meta\">Target: %s &nbsp;·&nbsp; Scan date: %s &nbsp;·&nbsp; Tool: %s %s</div></div>\n",
		html.EscapeString(r.Target),
		html.EscapeString(r.ScanDate.Format(time.RFC3339)),
		html.EscapeString(r.ToolName),
		html.EscapeString(r.ToolVersion),
	)

	counts := r.SeverityCounts()
	buf.WriteString("<div class=\"summary\">\n")
	for _, sev := range htmlSeverityOrder {
		color := htmlSeverityColors[sev]
		label := strings.ToUpper(string(sev))
		fmt.Fprintf(&buf,
			"<div class=\"badge\" style=\"border-color:%s\"><div class=\"count\" style=\"color:%s\">%d</div><div class=\"label\">%s</div></div>\n",
			color, color, counts[sev], label,
		)
	}
	buf.WriteString("</div>\n")

	for _, sev := range htmlSeverityOrder {
		band := r.FindingsBySeverity(sev)
		if len(band) == 0 {
			continue
		}
		color := htmlSeverityColors[sev]
		label := capitalize(string(sev))
		fmt.Fprintf(&buf, "<div class=\"section\"><h2>%s Findings</h2>\n", label)
		for _, finding := range band {
			writeHTMLFinding(&buf, finding, color)
		}
		buf.WriteString("</div>\n")
	}

	fmt.Fprintf(&buf, "<footer style=\"text-align:center;padding:1rem;color:#9e9e9e;font-size:.75rem\">Generated by %s</footer>\n", html.EscapeString(reportx.Watermark))
	buf.WriteString("</body>\n</html>\n")
	return buf.Bytes(), nil
}

func writeHTMLFinding(buf *bytes.Buffer, f reportx.Finding, color string) {
	fmt.Fprintf(buf, "<details>\n<summary><span class=\"sev\" style=\"background:%s\">%s</span> %s</summary>\n",
		color, strings.ToUpper(string(f.Severity)), html.EscapeString(f.Title),
	)
	buf.WriteString("<div class=\"finding-body\"><dl>\n")

	writeHTMLDT(buf, "URL", f.URL)
	if f.Parameter != "" {
		fmt.Fprintf(buf, "<dt>Parameter</dt><dd><code>%s</code></dd>\n", html.EscapeString(f.Parameter))
	}
	cwe := f.CWEID
	if f.CWEName != "" {
		cwe = fmt.Sprintf("%s \u2013 %s", f.CWEID, f.CWEName)
	}
	writeHTMLDT(buf, "CWE", cwe)

	var cvss string
	if f.CVSS40Score > 0 {
		cvss = fmt.Sprintf("%.1f (CVSS 4.0)", f.CVSS40Score)
	} else if f.CVSS31Score > 0 {
		cvss = fmt.Sprintf("%.1f (CVSS 3.1)", f.CVSS31Score)
	}
	writeHTMLDT(buf, "CVSS", cvss)
	writeHTMLDT(buf, "OWASP", f.OwaspTop10)
	fmt.Fprintf(buf, "<dt>Status</dt><dd>%s</dd>\n", html.EscapeString(string(f.Status)))
	if !f.FirstSeen.IsZero() {
		fmt.Fprintf(buf, "<dt>First seen</dt><dd>%s</dd>\n", f.FirstSeen.Format(time.RFC3339))
	}
	if !f.LastSeen.IsZero() {
		fmt.Fprintf(buf, "<dt>Last seen</dt><dd>%s</dd>\n", f.LastSeen.Format(time.RFC3339))
	}
	if f.FingerprintHash != "" {
		fmt.Fprintf(buf, "<dt>Fingerprint</dt><dd><code>%s</code></dd>\n", html.EscapeString(f.FingerprintHash))
	}
	if len(f.Tags) > 0 {
		fmt.Fprintf(buf, "<dt>Tags</dt><dd>%s</dd>\n", html.EscapeString(strings.Join(f.Tags, ", ")))
	}
	buf.WriteString("</dl>\n")

	if f.Description != "" {
		fmt.Fprintf(buf, "<div class=\"prose\"><h4>Description</h4><p>%s</p></div>\n", html.EscapeString(f.Description))
	}
	if f.Remediation != "" {
		fmt.Fprintf(buf, "<div class=\"prose\"><h4>Remediation</h4><p>%s</p></div>\n", html.EscapeString(f.Remediation))
	}
	if !f.Evidence.IsEmpty() {
		buf.WriteString("<details><summary>Evidence</summary>\n")
		if f.Evidence.HasStructured() {
			writeHTMLEvidenceStructured(buf, f.Evidence)
		} else {
			if f.Evidence.RawRequest != "" {
				fmt.Fprintf(buf, "<pre>%s</pre>\n", html.EscapeString(f.Evidence.RawRequest))
			}
			if f.Evidence.RawResponse != "" {
				fmt.Fprintf(buf, "<pre>%s</pre>\n", html.EscapeString(f.Evidence.RawResponse))
			}
		}
		buf.WriteString("</details>\n")
	}
	buf.WriteString("</div>\n</details>\n")
}

func writeHTMLEvidenceStructured(buf *bytes.Buffer, e reportx.Evidence) {
	if e.RequestMethod != "" || e.RequestURL != "" {
		method := html.EscapeString(e.RequestMethod)
		u := html.EscapeString(e.RequestURL)
		fmt.Fprintf(buf, "<pre>%s %s</pre>\n", method, u)
	}
	if e.ResponseStatus != 0 {
		fmt.Fprintf(buf, "<pre>HTTP %d</pre>\n", e.ResponseStatus)
	}
	if len(e.ResponseHeaders) > 0 {
		buf.WriteString("<pre>")
		keys := make([]string, 0, len(e.ResponseHeaders))
		for k := range e.ResponseHeaders {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			for _, v := range e.ResponseHeaders[k] {
				fmt.Fprintf(buf, "%s: %s\n", html.EscapeString(k), html.EscapeString(v))
			}
		}
		buf.WriteString("</pre>\n")
	}
	if len(e.RequestBody) > 0 {
		fmt.Fprintf(buf, "<pre>%s</pre>\n", html.EscapeString(string(e.RequestBody)))
	}
	if len(e.ResponseBody) > 0 {
		fmt.Fprintf(buf, "<pre>%s</pre>\n", html.EscapeString(string(e.ResponseBody)))
	}
}

func writeHTMLDT(buf *bytes.Buffer, label, value string) {
	if value == "" {
		return
	}
	fmt.Fprintf(buf, "<dt>%s</dt><dd>%s</dd>\n", label, html.EscapeString(value))
}

func (f *HTMLFormatter) MediaType() string     { return "text/html" }
func (f *HTMLFormatter) FileExtension() string { return ".html" }
