package format

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/cerberauth/reportx"
	"github.com/cerberauth/reportx/evidence"
)

type MarkdownFormatter struct {
	// ReferrerTag, when set, is appended as a "ref" query param to each
	// finding's URL so clicks from the report can be attributed back.
	ReferrerTag string
}

func NewMarkdownFormatter() *MarkdownFormatter { return &MarkdownFormatter{} }

// NewMarkdownFormatterWithReferrerTag returns a MarkdownFormatter that
// tags finding URLs with the given referrer tag (see ReferrerTag).
func NewMarkdownFormatterWithReferrerTag(tag string) *MarkdownFormatter {
	return &MarkdownFormatter{ReferrerTag: tag}
}

var severityOrder = []reportx.Severity{
	reportx.SeverityCritical,
	reportx.SeverityHigh,
	reportx.SeverityMedium,
	reportx.SeverityLow,
	reportx.SeverityInfo,
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func (f *MarkdownFormatter) Format(r *reportx.Report) ([]byte, error) {
	var buf bytes.Buffer

	title := r.Title
	if title == "" {
		title = defaultTitle
	}
	fmt.Fprintf(&buf, "# %s\n\n", title)
	fmt.Fprintf(&buf, "**Target:** %s | **Scan date:** %s | **Tool:** %s %s\n\n",
		r.Target,
		r.ScanDate.Format(time.RFC3339),
		r.ToolName,
		r.ToolVersion,
	)

	counts := r.SeverityCounts()
	buf.WriteString("## Summary\n\n")
	buf.WriteString("| Severity | Count |\n|----------|-------|\n")
	for _, sev := range severityOrder {
		n := counts[sev]
		fmt.Fprintf(&buf, "| %s | %d |\n", capitalize(string(sev)), n)
	}
	buf.WriteString("\n")

	for _, sev := range severityOrder {
		band := r.FindingsBySeverity(sev)
		if len(band) == 0 {
			continue
		}
		fmt.Fprintf(&buf, "## %s findings\n\n", capitalize(string(sev)))
		for _, finding := range band {
			writeFindingMD(&buf, finding, f.ReferrerTag)
		}
	}

	fmt.Fprintf(&buf, "---\n_Generated by %s_\n", reportx.Watermark)

	return buf.Bytes(), nil
}

func writeFindingMD(buf *bytes.Buffer, f reportx.Finding, referrerTag string) {
	fmt.Fprintf(buf, "### %s\n\n", f.Title)

	buf.WriteString("| Field | Value |\n|-------|-------|\n")
	if f.URL != "" {
		fmt.Fprintf(buf, "| URL | %s |\n", appendReferrerTag(f.URL, referrerTag))
	}
	if f.Parameter != "" {
		fmt.Fprintf(buf, "| Parameter | `%s` |\n", f.Parameter)
	}
	cweCell := f.CWEID
	if f.CWEName != "" {
		cweCell = fmt.Sprintf("%s – %s", f.CWEID, f.CWEName)
	}
	if cweCell != "" {
		fmt.Fprintf(buf, "| CWE | %s |\n", cweCell)
	}
	if f.CVSS40Score > 0 {
		fmt.Fprintf(buf, "| CVSS 4.0 | %.1f |\n", f.CVSS40Score)
	} else if f.CVSS31Score > 0 {
		fmt.Fprintf(buf, "| CVSS 3.1 | %.1f |\n", f.CVSS31Score)
	}
	if f.OwaspTop10 != "" {
		fmt.Fprintf(buf, "| OWASP | %s |\n", f.OwaspTop10)
	}
	fmt.Fprintf(buf, "| Status | %s |\n", string(f.Status))
	buf.WriteString("\n")

	if f.Description != "" {
		fmt.Fprintf(buf, "**Description**\n\n%s\n\n", f.Description)
	}
	if f.Remediation != "" {
		fmt.Fprintf(buf, "**Remediation**\n\n%s\n\n", f.Remediation)
	}

	switch ev := f.Evidence.(type) {
	case *evidence.HTTPEvidence:
		if !ev.IsEmpty() {
			buf.WriteString("<details><summary>Evidence</summary>\n\n")
			if ev.HasStructured() {
				writeMarkdownEvidenceStructured(buf, ev)
			} else {
				if ev.RawRequest != "" {
					buf.WriteString("```http\n")
					buf.WriteString(ev.RawRequest)
					buf.WriteString("\n```\n\n")
				}
				if ev.RawResponse != "" {
					buf.WriteString("```http\n")
					buf.WriteString(ev.RawResponse)
					buf.WriteString("\n```\n\n")
				}
			}
			buf.WriteString("</details>\n\n")
		}
	case *evidence.CustomEvidence:
		if !ev.IsEmpty() {
			buf.WriteString("<details><summary>Evidence</summary>\n\n")
			writeMarkdownEvidenceCustom(buf, ev)
			buf.WriteString("</details>\n\n")
		}
	}
}

func writeMarkdownEvidenceCustom(buf *bytes.Buffer, e *evidence.CustomEvidence) {
	keys := make([]string, 0, len(e.Data))
	for k := range e.Data {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	buf.WriteString("| Key | Value |\n|-----|-------|\n")
	for _, k := range keys {
		fmt.Fprintf(buf, "| %s | %s |\n", k, fmt.Sprintf("%v", e.Data[k]))
	}
	buf.WriteString("\n")
}

func writeMarkdownEvidenceStructured(buf *bytes.Buffer, e *evidence.HTTPEvidence) {
	if e.RequestMethod != "" || e.RequestURL != "" {
		fmt.Fprintf(buf, "```http\n%s %s\n```\n\n", e.RequestMethod, e.RequestURL)
	}
	if e.ResponseStatus != 0 {
		fmt.Fprintf(buf, "```\nHTTP %d\n```\n\n", e.ResponseStatus)
	}
	if len(e.ResponseHeaders) > 0 {
		buf.WriteString("```\n")
		keys := make([]string, 0, len(e.ResponseHeaders))
		for k := range e.ResponseHeaders {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			for _, v := range e.ResponseHeaders[k] {
				fmt.Fprintf(buf, "%s: %s\n", k, v)
			}
		}
		buf.WriteString("```\n\n")
	}
	if len(e.RequestBody) > 0 {
		fmt.Fprintf(buf, "```\n%s\n```\n\n", string(e.RequestBody))
	}
	if len(e.ResponseBody) > 0 {
		fmt.Fprintf(buf, "```\n%s\n```\n\n", string(e.ResponseBody))
	}
}

func (f *MarkdownFormatter) MediaType() string     { return "text/markdown" }
func (f *MarkdownFormatter) FileExtension() string { return ".md" }
