package format

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/cerberauth/reportx"
	"github.com/cerberauth/reportx/evidence"
)

const (
	ansiReset   = "\033[0m"
	ansiBold    = "\033[1m"
	ansiDim     = "\033[2m"
	ansiRed     = "\033[31m"
	ansiYellow  = "\033[33m"
	ansiCyan    = "\033[36m"
	ansiBlue    = "\033[34m"
	ansiBoldRed = "\033[1;31m"
	ansiGreen   = "\033[32m"
)

var severityColor = map[reportx.Severity]string{
	reportx.SeverityCritical: ansiBoldRed,
	reportx.SeverityHigh:     ansiRed,
	reportx.SeverityMedium:   ansiYellow,
	reportx.SeverityLow:      ansiCyan,
	reportx.SeverityInfo:     ansiBlue,
}

type TerminalFormatter struct {
	NoColor bool
}

func NewTerminalFormatter() *TerminalFormatter { return &TerminalFormatter{} }

func NewTerminalFormatterNoColor() *TerminalFormatter { return &TerminalFormatter{NoColor: true} }

func (f *TerminalFormatter) color(code, s string) string {
	if f.NoColor {
		return s
	}
	return code + s + ansiReset
}

func (f *TerminalFormatter) bold(s string) string { return f.color(ansiBold, s) }
func (f *TerminalFormatter) dim(s string) string  { return f.color(ansiDim, s) }
func (f *TerminalFormatter) severityStr(s reportx.Severity) string {
	label := strings.ToUpper(string(s))
	c, ok := severityColor[s]
	if !ok || f.NoColor {
		return label
	}
	return c + label + ansiReset
}

func (f *TerminalFormatter) Format(r *reportx.Report) ([]byte, error) {
	var buf bytes.Buffer
	w := &buf

	title := r.Title
	if title == "" {
		title = defaultTitle
	}

	fmt.Fprintf(w, "\n%s\n", f.bold(title))
	fmt.Fprintf(w, "%s\n\n", strings.Repeat("─", 60))
	fmt.Fprintf(w, "  %s  %s\n", f.dim("Target:   "), r.Target)
	if r.ToolName != "" {
		fmt.Fprintf(w, "  %s  %s %s\n", f.dim("Tool:     "), r.ToolName, r.ToolVersion)
	}
	fmt.Fprintf(w, "  %s  %s\n\n", f.dim("Scan date:"), r.ScanDate.UTC().Format(time.RFC3339))

	counts := r.SeverityCounts()
	total := 0
	for _, n := range counts {
		total += n
	}

	fmt.Fprintf(w, "%s\n", f.bold("SUMMARY"))
	fmt.Fprintf(w, "%s\n", strings.Repeat("─", 30))

	for _, sev := range severityOrder {
		n := counts[sev]
		bar := ""
		if n > 0 && !f.NoColor {
			bar = severityColor[sev] + strings.Repeat("█", min(n, 20)) + ansiReset
		}
		fmt.Fprintf(w, "  %-10s %3d  %s\n", f.severityStr(sev), n, bar)
	}
	fmt.Fprintf(w, "%s\n", strings.Repeat("─", 30))
	fmt.Fprintf(w, "  %-10s %3d\n\n", f.bold("Total"), total)

	for _, sev := range severityOrder {
		band := r.FindingsBySeverity(sev)
		if len(band) == 0 {
			continue
		}

		heading := fmt.Sprintf("%s FINDINGS (%d)", strings.ToUpper(string(sev)), len(band))
		fmt.Fprintf(w, "%s\n", f.color(severityColor[sev], f.bold(heading)))
		fmt.Fprintf(w, "%s\n", strings.Repeat("─", 60))

		for i, finding := range band {
			f.writeFinding(w, finding)
			if i < len(band)-1 {
				fmt.Fprintf(w, "%s\n", f.dim(strings.Repeat("·", 60)))
			}
		}
		fmt.Fprintln(w)
	}

	fmt.Fprintf(w, "%s\n", f.dim("Generated by "+reportx.Watermark))

	return buf.Bytes(), nil
}

func (f *TerminalFormatter) writeFinding(w *bytes.Buffer, fi reportx.Finding) {
	fmt.Fprintf(w, "  %s  %s\n", f.color(severityColor[fi.Severity], "■"), f.bold(fi.Title))

	if fi.URL != "" {
		fmt.Fprintf(w, "    %s  %s\n", f.dim("URL:      "), fi.URL)
	}
	if fi.Parameter != "" {
		fmt.Fprintf(w, "    %s  %s\n", f.dim("Parameter:"), fi.Parameter)
	}
	cwe := fi.CWEID
	if fi.CWEName != "" {
		cwe = fi.CWEID + " – " + fi.CWEName
	}
	if cwe != "" {
		fmt.Fprintf(w, "    %s  %s\n", f.dim("CWE:      "), cwe)
	}
	if fi.CVSS40Score > 0 {
		fmt.Fprintf(w, "    %s  %.1f  %s\n", f.dim("CVSS 4.0: "), fi.CVSS40Score, fi.CVSS40Vector)
	} else if fi.CVSS31Score > 0 {
		fmt.Fprintf(w, "    %s  %.1f  %s\n", f.dim("CVSS 3.1: "), fi.CVSS31Score, fi.CVSS31Vector)
	}
	if fi.OwaspTop10 != "" {
		fmt.Fprintf(w, "    %s  %s\n", f.dim("OWASP:    "), fi.OwaspTop10)
	}
	fmt.Fprintf(w, "    %s  %s\n", f.dim("Status:   "), string(fi.Status))
	if len(fi.Tags) > 0 {
		fmt.Fprintf(w, "    %s  %s\n", f.dim("Tags:     "), strings.Join(fi.Tags, ", "))
	}

	switch ev := fi.Evidence.(type) {
	case *evidence.HTTPEvidence:
		if ev.HasStructured() {
			if ev.RequestMethod != "" || ev.RequestURL != "" {
				fmt.Fprintf(w, "    %s  %s %s", f.dim("Evidence: "), ev.RequestMethod, ev.RequestURL)
				if ev.ResponseStatus != 0 {
					fmt.Fprintf(w, " → %d", ev.ResponseStatus)
				}
				fmt.Fprintln(w)
			} else if ev.ResponseStatus != 0 {
				fmt.Fprintf(w, "    %s  HTTP %d\n", f.dim("Evidence: "), ev.ResponseStatus)
			}
		}
	case *evidence.CustomEvidence:
		if !ev.IsEmpty() {
			keys := make([]string, 0, len(ev.Data))
			for k := range ev.Data {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			parts := make([]string, 0, len(keys))
			for _, k := range keys {
				parts = append(parts, fmt.Sprintf("%s=%v", k, ev.Data[k]))
			}
			fmt.Fprintf(w, "    %s  %s\n", f.dim("Evidence: "), strings.Join(parts, " "))
		}
	}

	if fi.Description != "" {
		fmt.Fprintf(w, "\n    %s\n", f.bold("Description"))
		for _, line := range wrapLines(fi.Description, 72) {
			fmt.Fprintf(w, "      %s\n", line)
		}
	}
	if fi.Remediation != "" {
		fmt.Fprintf(w, "\n    %s\n", f.color(ansiGreen, f.bold("Remediation")))
		for _, line := range wrapLines(fi.Remediation, 72) {
			fmt.Fprintf(w, "      %s\n", line)
		}
	}
	fmt.Fprintln(w)
}

func wrapLines(text string, maxWidth int) []string {
	var out []string
	for _, paragraph := range strings.Split(text, "\n") {
		words := strings.Fields(paragraph)
		if len(words) == 0 {
			out = append(out, "")
			continue
		}
		line := words[0]
		for _, w := range words[1:] {
			if len(line)+1+len(w) > maxWidth {
				out = append(out, line)
				line = w
			} else {
				line += " " + w
			}
		}
		out = append(out, line)
	}
	return out
}

func (f *TerminalFormatter) MediaType() string     { return "text/plain" }
func (f *TerminalFormatter) FileExtension() string { return ".txt" }
